package:
  name: mycogap
  version: 1.7.0

source:
  path: .

build:
  number: 0
  noarch: generic
  script: |
    install -d "$PREFIX/bin"
    install -d "$PREFIX/lib/R/library/mycogap/ref"
    install -m 0755 bin/mycogap "$PREFIX/bin/mycogap"
    install -m 0644 ref/macrofungi_list.csv "$PREFIX/lib/R/library/mycogap/ref/macrofungi_list.csv"
    install -m 0644 ref/sh_general_release_dynamic_all_19.02.2025.fasta.gz "$PREFIX/lib/R/library/mycogap/ref/sh_general_release_dynamic_all_19.02.2025.fasta.gz"

requirements:
  run:
    - r-base >=4.4
    - bioconductor-dada2
    - bioconductor-biostrings
    - bioconductor-phyloseq
    - bioconductor-microbiome
    - r-optparse
    - r-tidyverse
    - r-data.table
    - r-vegan
    - r-fs
    - r-r.utils
    - seqkit
    - itsx
    - vsearch

test:
  commands:
    - mycogap --help
    - test -r "$PREFIX/lib/R/library/mycogap/ref/macrofungi_list.csv"
    - test -r "$PREFIX/lib/R/library/mycogap/ref/sh_general_release_dynamic_all_19.02.2025.fasta.gz"

about:
  home: https://github.com/WeStrainGroup/MycoGAP
  license: CC-BY-NC-SA-4.0
  license_file: LICENSE
  summary: "Accurate, human gut-focused, ITS-aware analysis with MycoGAP"
  description: |
    MycoGAP is an accurate, human gut-focused, ITS-aware workflow for
    standardized analysis of heterogeneous datasets, including paired-end or
    single-end Illumina and PacBio ITS data.
  dev_url: https://github.com/WeStrainGroup/MycoGAP
